[font]
size = 16.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 208
lines = 70

[window.position]
x = 590
y = 186

[general]
import = ["/Users/maf/.config/alacritty/themes/themes/hyper.toml"]
