set viminfofile=$XDG_STATE_HOME/vim/viminfo
let g:netrw_home='$XDG_STATE_HOME/vim'

"colorscheme lunaperche
syntax on

set autoindent
set autoread
set cinoptions=:0,l1,t0
set clipboard=unnamedplus  " requires vim to be compiled with +clipboard option
set linebreak
set nobackup
set nowritebackup
set scrolloff=8
set shiftwidth=0
set sidescrolloff=8
set tabstop=4
set wildoptions=pum
set wrap

let &t_SI = "\e[6 q"  " set cursor to bar when entering insert mode
let &t_EI = "\e[2 q"  " set cursor to block when exiting insert mode

nnoremap <Space> <Nop>
let mapleader = " "
nnoremap <Leader>f :FZF<CR>
nnoremap <Leader>h :let @/ = ""<CR>
nnoremap <Leader>n :set number!<CR>
nnoremap <Leader>t :tabnew<CR>
nnoremap <Leader>w :set wrap!<CR>
nnoremap H :bp<CR>
nnoremap L :bn<CR>
nnoremap <Tab> :tabnext<CR>
nnoremap <S-Tab> :tabprevious<CR>
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
inoremap <C-f> <Right>
inoremap <C-b> <Left>

augroup CIndent
    autocmd!
    autocmd FileType c,cpp setlocal cindent
augroup END

"autocmd BufWritePost *.c,*.h silent !maf-indent %
