"colorscheme lunaperche
syntax on

let &t_SI = "\e[6 q"  " set cursor to bar when entering insert mode
let &t_EI = "\e[2 q"  " set cursor to block when exiting insert mode
let g:netrw_home='$XDG_STATE_HOME/vim'

set autoindent
set autoread
set nobackup
set clipboard=unnamedplus  " requires vim to be compiled with +clipboard option
set linebreak
set scrolloff=8
set shiftwidth=0
set sidescrolloff=8
set tabstop=4
set viminfofile=$XDG_STATE_HOME/vim/viminfo
set wildoptions=pum
set wrap
set nowritebackup

nnoremap <Space> <Nop>
let mapleader = " "
nnoremap <Leader>b <Cmd>Buffers<CR>
nnoremap <Leader>c :colorscheme 
nnoremap <Leader>f <Cmd>FZF<CR>
nnoremap <Leader>g <Cmd>Rg<CR>
nnoremap <Leader>h <Cmd>let @/ = ""<CR>
nnoremap <Leader>n <Cmd>set number!<CR>
nnoremap <Leader>s <Cmd>if exists("g:syntax_on") \| syntax off \| else \| syntax enable \| endif<CR>
nnoremap <Leader>t <Cmd>tabnew<CR>
nnoremap <Leader>w <Cmd>set wrap!<CR>
nnoremap <Esc> <Cmd>nohlsearch<CR>
nnoremap H <Cmd>bprevious<CR>
nnoremap L <Cmd>bnext<CR>
nnoremap <Tab> <Cmd>tabnext<CR>
nnoremap <S-Tab> <Cmd>tabprevious<CR>
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
inoremap <C-f> <Right>
inoremap <C-b> <Left>
inoremap ( ()<Left>
inoremap [ []<Left>
inoremap { {}<Left>
inoremap " ""<Left>

augroup CIndent
    autocmd!
    autocmd FileType c,cpp setlocal cindent
    autocmd Filetype c,cpp setlocal cinoptions=:0,l1,t0
"    autocmd FileType c,cpp setlocal expandtab
    autocmd FileType c,cpp setlocal formatprg=maf-indent
augroup END
