#!/usr/bin/env bash

dwm_battery() {
  # Change BAT# to whatever your battery is identified as. Typically BAT0 or BAT1.
  CHARGE=$(cat /sys/class/power_supply/BAT0/capacity)
  printf "%s%%" "$CHARGE"
}

# statusbar loop

while true; do
  xsetroot -name " $(dwm_battery) | $(date +"%F %R")"
  sleep 1s
done &

# start some nice things

xset -dpms
xset s off

sxhkd &
unclutter &
exec dwm
