#!/usr/bin/env bash

# Git status indicator
if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
	if [[ -n $(git status --porcelain) ]]; then
		git=" ${red}*${reset} "
	else
		if [[ $(git rev-list --count @{u}..HEAD) -gt 0 ]]; then
			git=" ${yellow}*${reset} "
		else
			git=" ${green}*${reset} "
		fi
	fi
else
	git=""
fi

# To use the prompt with git status indicator,
# include the following line in ~/.bashrc
#PROMPT_COMMAND="source $HOME/dotfiles/bash/prompt"

# Special characters:
# \u  username
# \h  hostname
# \W  basename of $PWD
# \$  $ if regular user, # if root

# Colorful bash prompt inspired by LARBS
red="\[\e[1;31m\]"
yellow="\[\e[1;33m\]"
green="\[\e[1;32m\]"
blue="\[\e[1;34m\]"
purple="\[\e[1;35m\]"
bold="\[\e[1;0m\]"
reset="\[\e[0m\]"
export PS1="${red}[${yellow}\u${green}@${blue}\h ${purple}\W${red}]${git}${bold}\$ ${reset}"

# # Simple bash prompt for Fedora
# blue="\[\e[1;34m\]" # bold blue
# bold="\[\e[1;0m\]"
# reset="\[\e[0m\]"
# export PS1="${blue}[${bold}\u@\h \W${blue}]${reset}\\$ "

# # Simple bash prompt for Arch
# blue="\[\e[1;38;2;51;170;221m\]"
# reset="\[\e[0m\]"
# export PS1="${blue}[${reset}\u@\h \W${blue}]${reset}\\$ "
