[language-server.clangd]
command = "clangd"

[[language]]
name = "c"
auto-format = true
language-servers = ["clangd"]
formatter = { command = "maf-indent" }
indent = { tab-width = 8 , unit = "\t" }
rulers = [80]
